"""Padding-token dose-response ablation for i2i->i2i color & style transfer.

Re-runs the known-working color (block 17 / Single-9) and style (block 7 /
MM-7) i2i->i2i pairings at four prompt lengths that leave ~494 / ~322 / ~149 /
~0 of the 512 text slots as padding, with ``--text-seq-len`` pinned at 512 so
the joint sequence length and RoPE range never change. If padding tokens are
the carriers of the transferred color/style, the ``padding_only`` patch should
weaken monotonically as padding slots disappear; if ``content_only`` instead
*rises* as content grows, the mechanism is spare capacity rather than padding
positions per se.

(This supersedes the earlier ``reproduce_longprompt_padding_ablation.py``,
which varied ``--text-seq-len`` 512 vs 1024 and thereby confounded padding
count with total sequence length.)

Each cell is an independent subprocess; ``--skip-if-completed`` makes it
resumable. Tasks + pair files are generated by
``build_padding_ablation_tasks.py`` / ``build_pairs_padding_ablation.py``
(committed under ``data/tasks/*_padding/`` and ``pairs/*_p<NNN>.txt``).

Usage::

    uv run python scripts/reproduce_padding_ablation.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from experiments.i2i_to_i2i_patching.build_padding_ablation_tasks import (  # noqa: E402
    PADDING_LEVELS,
    level_slug,
)

ALL_TEXT_TOKEN_MODES = ("all", "padding_only", "content_only")
# Content-span splits: which half of the content span mediates the transfer,
# the original short instruction's tokens or the appended filler's. Degenerate
# at p494 (the prompt IS the instruction), so they run at the longer levels.
SPLIT_TEXT_TOKEN_MODES = ("instruction_only", "filler_only")
TEXT_SEQ_LEN = 512  # pinned: only the content/padding split varies
PAIRS_DIR = REPO_ROOT / "experiments" / "i2i_to_i2i_patching" / "pairs"

# (family, block_range_first, block_range_last, pairs_file_stem)
FAMILIES: list[tuple[str, str, str, str]] = [
    ("color", "17", "17", "single9_4step_color"),
    ("style_to_real", "7", "7", "mm7_4step_style_to_real"),
]


def _run(name: str, lo: str, hi: str, pairs_stem: str, slug: str) -> None:
    pairs_path = PAIRS_DIR / f"{pairs_stem}_{slug}.txt"
    assert pairs_path.exists(), f"missing pairs file: {pairs_path}"
    subdir = f"{name}_{slug}"
    modes = list(ALL_TEXT_TOKEN_MODES)
    if slug != level_slug(494):
        modes += list(SPLIT_TEXT_TOKEN_MODES)
    argv = [
        "uv", "run", "python", "-m", "experiments.i2i_to_i2i_patching.i2i_to_i2i_patch",
        "--pair-list", str(pairs_path),
        "--block-range", lo, hi,
        "--num-inference-steps", "4",
        "--text-seq-len", str(TEXT_SEQ_LEN),
        "--text-token-mode", *modes,
        "--results-subdir", subdir,
        "--skip-if-completed",
    ]
    print(f"\n=== i2i_to_i2i_patching / {subdir} ===")
    print(">>> " + " ".join(argv))
    result = subprocess.run(argv, cwd=REPO_ROOT, check=False)
    if result.returncode != 0:
        print(f"[FAIL] cell={subdir} returncode={result.returncode}", file=sys.stderr)
        sys.exit(result.returncode)


def main() -> None:
    n = 0
    for name, lo, hi, pairs_stem in FAMILIES:
        for target in PADDING_LEVELS:
            _run(name, lo, hi, pairs_stem, level_slug(target))
            n += 1
    print(f"\nDone. Ran {n} padding-ablation cells.")


if __name__ == "__main__":
    main()
